name: Python application workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy tushare yfinance matplotlib scikit-learn
    - name: Set Tushare Token
      env:
        TUTOKEN: ${{ secrets.TUTOKEN }}
      run: |
        python MLP.py
        
