name: Python application workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy tushare yfinance matplotlib scikit-learn
    - name: Set Tushare Token
      env:
        TUTOKEN: ${{ secrets.TUTOKEN }}
      run: |
        echo "Setting up Tushare token..."
        echo "export TUTOKEN=$TUTOKEN" >> $GITHUB_ENV
    - name: Execute script
      run: |
        python -ic "import os; import tushare as ts; ts.set_token(os.getenv('TUTOKEN')); print('Tushare token set successfully.');"
        python MLP.py
        
